language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - pypy
# command to run tests
script:
 - export PYTHONPATH=`pwd`/six-*.egg
 # testing fix for https://bitbucket.org/hpk42/pytest/issue/555
 - pip install --pre -i https://devpi.net/hpk/dev/ --upgrade pytest
 - python setup.py test
 - python setup.py ptr
 - python ez_setup.py --version 5.4.1
